package com.worldmonitor.app

import android.annotation.SuppressLint
import android.app.Activity
import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.view.KeyEvent
import android.view.View
import android.view.WindowManager
import android.webkit.WebChromeClient
import android.webkit.WebResourceRequest
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import android.widget.ProgressBar
import android.widget.Toast

class MainActivity : Activity() {

    private lateinit var webView: WebView
    private lateinit var progressBar: ProgressBar
    private val handler = Handler(Looper.getMainLooper())
    private var isTranslationEnabled = true

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        // 全屏 + 保持屏幕常亮
        window.addFlags(
            WindowManager.LayoutParams.FLAG_FULLSCREEN or
            WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON
        )
        
        // 隐藏系统UI
        hideSystemUI()
        
        setContentView(R.layout.activity_main)
        
        webView = findViewById(R.id.webView)
        progressBar = findViewById(R.id.progressBar)
        
        setupWebView()
        
        // 加载 WorldMonitor
        webView.loadUrl("https://worldmonitor.app")
    }
    
    @SuppressLint("SetJavaScriptEnabled")
    private fun setupWebView() {
        val settings = webView.settings
        
        // 启用 JavaScript
        settings.javaScriptEnabled = true
        settings.domStorageEnabled = true
        settings.databaseEnabled = true
        settings.cacheMode = WebSettings.LOAD_DEFAULT
        
        // 适配大屏
        settings.useWideViewPort = true
        settings.loadWithOverviewMode = true
        
        // 缩放控制
        settings.setSupportZoom(true)
        settings.builtInZoomControls = true
        settings.displayZoomControls = false
        
        // 媒体播放
        settings.mediaPlaybackRequiresUserGesture = false
        
        // 混合内容
        settings.mixedContentMode = WebSettings.MIXED_CONTENT_ALWAYS_ALLOW
        
        // 性能优化
        settings.setRenderPriority(WebSettings.RenderPriority.HIGH)
        settings.javaScriptCanOpenWindowsAutomatically = true
        
        webView.webChromeClient = WebChromeClient()
        
        webView.webViewClient = object : WebViewClient() {
            override fun onPageFinished(view: WebView?, url: String?) {
                super.onPageFinished(view, url)
                progressBar.visibility = View.GONE
                
                // 页面加载完成后执行初始化
                handler.postDelayed({
                    setChineseLanguage()
                    if (isTranslationEnabled) {
                        injectTranslationScript()
                    }
                }, 3000)
            }
            
            override fun shouldOverrideUrlLoading(
                view: WebView?, 
                request: WebResourceRequest?
            ): Boolean {
                return false
            }
        }
    }
    
    /**
     * 注入翻译脚本
     */
    private fun injectTranslationScript() {
        val script = """
            (function() {
                if (window.__wmTranslator) return;
                window.__wmTranslator = true;
                
                console.log('[WorldMonitor] Translator loaded');
                
                // 翻译词典
                const dict = {
                    'breaking': '突发',
                    'urgent': '紧急',
                    'alert': '警报',
                    'just in': '刚刚',
                    'update': '更新',
                    'developing': '进展中',
                    'conflict': '冲突',
                    'war': '战争',
                    'attack': '袭击',
                    'military': '军事',
                    'armed': '武装',
                    'forces': '部队',
                    'strike': '打击',
                    'bombing': '轰炸',
                    'explosion': '爆炸',
                    'fire': '火灾',
                    'shooting': '枪击',
                    'killed': '死亡',
                    'dead': '死亡',
                    'casualties': '伤亡',
                    'injured': '受伤',
                    'hostage': '人质',
                    'kidnapped': '被绑架',
                    'captured': '被俘',
                    'invasion': '入侵',
                    'offensive': '攻势',
                    'assault': '攻击',
                    'raid': '突袭',
                    'siege': '围困',
                    'ceasefire': '停火',
                    'truce': '休战',
                    'peace': '和平',
                    'negotiations': '谈判',
                    'diplomatic': '外交',
                    'sanctions': '制裁',
                    'embargo': '禁运',
                    'treaty': '条约',
                    'agreement': '协议',
                    'alliance': '联盟',
                    'cooperation': '合作',
                    'tensions': '紧张局势',
                    'crisis': '危机',
                    'emergency': '紧急情况',
                    'state of emergency': '紧急状态',
                    'evacuation': '撤离',
                    'rescue': '救援',
                    'humanitarian': '人道主义',
                    'aid': '援助',
                    'refugees': '难民',
                    'displaced': '流离失所',
                    'protest': '抗议',
                    'demonstration': '示威',
                    'riot': '骚乱',
                    'unrest': '动荡',
                    'clash': '冲突',
                    'confrontation': '对抗',
                    'government': '政府',
                    'president': '总统',
                    'prime minister': '总理',
                    'minister': '部长',
                    'official': '官员',
                    'leader': '领导人',
                    'parliament': '议会',
                    'congress': '国会',
                    'senate': '参议院',
                    'election': '选举',
                    'vote': '投票',
                    'campaign': '竞选',
                    'party': '政党',
                    'opposition': '反对派',
                    'reform': '改革',
                    'policy': '政策',
                    'law': '法律',
                    'bill': '法案',
                    'regulation': '法规',
                    'ban': '禁令',
                    'restriction': '限制',
                    'border': '边境',
                    'territory': '领土',
                    'airspace': '领空',
                    'waters': '水域',
                    'zone': '区域',
                    'region': '地区',
                    'city': '城市',
                    'capital': '首都',
                    'province': '省',
                    'state': '州',
                    'district': '区',
                    'village': '村庄',
                    'checkpoint': '检查站',
                    'border crossing': '边境口岸',
                    'airport': '机场',
                    'port': '港口',
                    'harbor': '海港',
                    'base': '基地',
                    'facility': '设施',
                    'installation': '设施',
                    'plant': '工厂',
                    'refinery': '炼油厂',
                    'pipeline': '管道',
                    'power plant': '发电厂',
                    'nuclear': '核',
                    'reactor': '反应堆',
                    'radiation': '辐射',
                    'missile': '导弹',
                    'rocket': '火箭',
                    'drone': '无人机',
                    'aircraft': '飞机',
                    'jet': '喷气式飞机',
                    'helicopter': '直升机',
                    'fighter': '战斗机',
                    'bomber': '轰炸机',
                    'tank': '坦克',
                    'vehicle': '车辆',
                    'ship': '舰船',
                    'vessel': '船只',
                    'submarine': '潜艇',
                    'carrier': '航母',
                    'fleet': '舰队',
                    'navy': '海军',
                    'army': '陆军',
                    'air force': '空军',
                    'marines': '海军陆战队',
                    'special forces': '特种部队',
                    'intelligence': '情报',
                    'security': '安全',
                    'defense': '国防',
                    'police': '警察',
                    'law enforcement': '执法',
                    'militia': '民兵',
                    'rebels': '叛军',
                    'insurgents': '叛乱分子',
                    'terrorists': '恐怖分子',
                    'extremists': '极端分子',
                    'cyber': '网络',
                    'hack': '黑客',
                    'cyberattack': '网络攻击',
                    'malware': '恶意软件',
                    'ransomware': '勒索软件',
                    'data breach': '数据泄露',
                    'surveillance': '监控',
                    'espionage': '间谍',
                    'satellite': '卫星',
                    'space': '太空',
                    'orbit': '轨道',
                    'launch': '发射',
                    'rocket launch': '火箭发射',
                    'missile launch': '导弹发射',
                    'test': '测试',
                    'drill': '演习',
                    'exercise': '演习',
                    'training': '训练',
                    'deployment': '部署',
                    'mobilization': '动员',
                    'demobilization': '复员',
                    'withdrawal': '撤退',
                    'retreat': '撤退',
                    'surrender': '投降',
                    'defeat': '失败',
                    'victory': '胜利',
                    'occupied': '被占领',
                    'liberated': '解放',
                    'recaptured': '收复',
                    'advanced': '推进',
                    'approaching': '接近',
                    'surrounded': '被包围',
                    'trapped': '被困',
                    'cut off': '被切断',
                    'blocked': '被封锁',
                    'suspended': '暂停',
                    'halted': '停止',
                    'resumed': '恢复',
                    'delayed': '延迟',
                    'cancelled': '取消',
                    'postponed': '推迟',
                    'scheduled': '计划',
                    'expected': '预计',
                    'estimated': '估计',
                    'approximately': '大约',
                    'confirmed': '确认',
                    'unconfirmed': '未确认',
                    'reported': '据报道',
                    'according to': '根据',
                    'sources': '消息来源',
                    'officials': '官员',
                    'spokesperson': '发言人',
                    'statement': '声明',
                    'announcement': '公告',
                    'press release': '新闻稿',
                    'briefing': '简报',
                    'conference': '会议',
                    'meeting': '会晤',
                    'summit': '峰会',
                    'talks': '会谈',
                    'discussions': '讨论',
                    'negotiations': '谈判',
                    'deal': '协议',
                    'agreement reached': '达成协议',
                    'signed': '签署',
                    'ratified': '批准',
                    'implemented': '实施',
                    'violated': '违反',
                    'breached': '破坏',
                    'withdraw': '退出',
                    'suspended': '暂停',
                    'expelled': '驱逐',
                    'recalled': '召回',
                    'ambassador': '大使',
                    'diplomat': '外交官',
                    'envoy': '特使',
                    'delegation': '代表团',
                    'mission': '使团',
                    'consulate': '领事馆',
                    'embassy': '大使馆',
                    'trade': '贸易',
                    'economy': '经济',
                    'economic': '经济的',
                    'financial': '金融',
                    'market': '市场',
                    'stock market': '股市',
                    'exchange': '交易所',
                    'currency': '货币',
                    'dollar': '美元',
                    'euro': '欧元',
                    'yuan': '人民币',
                    'yen': '日元',
                    'pound': '英镑',
                    'oil': '石油',
                    'gas': '天然气',
                    'energy': '能源',
                    'price': '价格',
                    'cost': '成本',
                    'budget': '预算',
                    'spending': '支出',
                    'investment': '投资',
                    'fund': '基金',
                    'loan': '贷款',
                    'debt': '债务',
                    'inflation': '通货膨胀',
                    'recession': '衰退',
                    'growth': '增长',
                    'gdp': 'GDP',
                    'unemployment': '失业',
                    'jobs': '就业',
                    'wages': '工资',
                    'strike': '罢工',
                    'union': '工会',
                    'workers': '工人',
                    'employees': '员工',
                    'company': '公司',
                    'corporation': '企业',
                    'industry': '工业',
                    'sector': '部门',
                    'production': '生产',
                    'manufacturing': '制造业',
                    'supply chain': '供应链',
                    'shortage': '短缺',
                    'surplus': '过剩',
                    'import': '进口',
                    'export': '出口',
                    'tariff': '关税',
                    'tax': '税收',
                    'subsidy': '补贴',
                    'privatization': '私有化',
                    'nationalization': '国有化',
                    'merger': '合并',
                    'acquisition': '收购',
                    'bankruptcy': '破产',
                    'bailout': '救助',
                    'rescue package': '救援方案',
                    'stimulus': '刺激',
                    'infrastructure': '基础设施',
                    'construction': '建设',
                    'project': '项目',
                    'development': '发展',
                    'modernization': '现代化',
                    'upgrade': '升级',
                    'repair': '维修',
                    'damage': '损坏',
                    'destroyed': '被毁',
                    'collapsed': '倒塌',
                    'fire': '火灾',
                    'flood': '洪水',
                    'earthquake': '地震',
                    'tsunami': '海啸',
                    'hurricane': '飓风',
                    'typhoon': '台风',
                    'tornado': '龙卷风',
                    'storm': '风暴',
                    'drought': '干旱',
                    'famine': '饥荒',
                    'epidemic': '流行病',
                    'pandemic': '大流行',
                    'virus': '病毒',
                    'disease': '疾病',
                    'outbreak': '爆发',
                    'infection': '感染',
                    'vaccine': '疫苗',
                    'treatment': '治疗',
                    'hospital': '医院',
                    'healthcare': '医疗',
                    'medical': '医学',
                    'patient': '患者',
                    'doctor': '医生',
                    'nurse': '护士',
                    'ambulance': '救护车',
                    'emergency services': '紧急服务',
                    'search and rescue': '搜救',
                    'relief': '救援',
                    'shelter': '避难所',
                    'camp': '营地',
                    'food': '食物',
                    'water': '水',
                    'medicine': '药品',
                    'supply': '供应',
                    'distribution': '分发',
                    'donation': '捐赠',
                    'funding': '资金',
                    'grant': '拨款',
                    'loan': '贷款',
                    'assistance': '援助',
                    'support': '支持',
                    'help': '帮助',
                    'volunteers': '志愿者',
                    'ngo': '非政府组织',
                    'un': '联合国',
                    'red cross': '红十字会',
                    'who': '世卫组织',
                    'nato': '北约',
                    'eu': '欧盟',
                    'us': '美国',
                    'china': '中国',
                    'russia': '俄罗斯',
                    'uk': '英国',
                    'france': '法国',
                    'germany': '德国',
                    'japan': '日本',
                    'india': '印度',
                    'brazil': '巴西',
                    'israel': '以色列',
                    'palestine': '巴勒斯坦',
                    'ukraine': '乌克兰',
                    'iran': '伊朗',
                    'north korea': '朝鲜',
                    'south korea': '韩国',
                    'taiwan': '台湾',
                    'hong kong': '香港',
                    'middle east': '中东',
                    'europe': '欧洲',
                    'asia': '亚洲',
                    'africa': '非洲',
                    'americas': '美洲',
                    'pacific': '太平洋',
                    'arctic': '北极',
                    'antarctica': '南极',
                    'mediterranean': '地中海',
                    'baltic': '波罗的海',
                    'black sea': '黑海',
                    'caspian': '里海',
                    'red sea': '红海',
                    'gulf': '海湾',
                    'strait': '海峡',
                    'channel': '海峡',
                    'peninsula': '半岛',
                    'island': '岛屿',
                    'mountain': '山脉',
                    'river': '河流',
                    'lake': '湖泊',
                    'desert': '沙漠',
                    'forest': '森林',
                    'jungle': '丛林',
                    ' plains': '平原',
                    'valley': '山谷',
                    'coast': '海岸',
                    'beach': '海滩',
                    'port': '港口',
                    'harbor': '海港',
                    'bay': '海湾',
                    'cape': '海角',
                    'today': '今天',
                    'yesterday': '昨天',
                    'tomorrow': '明天',
                    'this morning': '今早',
                    'this afternoon': '今天下午',
                    'this evening': '今晚',
                    'tonight': '今晚',
                    'overnight': '夜间',
                    'early': '早些时候',
                    'late': '晚些时候',
                    'soon': '很快',
                    'immediately': '立即',
                    'urgently': '紧急',
                    'asap': '尽快',
                    'deadline': '截止日期',
                    'timeline': '时间表',
                    'schedule': '日程',
                    'agenda': '议程',
                    'priority': '优先',
                    'high priority': '高优先级',
                    'low priority': '低优先级',
                    'critical': '关键',
                    'serious': '严重',
                    'severe': '严峻',
                    'significant': '重大',
                    'major': '主要',
                    'minor': '次要',
                    'slight': '轻微',
                    'possible': '可能',
                    'likely': '很可能',
                    'unlikely': '不太可能',
                    'probable': '大概',
                    'improbable': '不太可能',
                    'certain': '确定',
                    'uncertain': '不确定',
                    'clear': '明确',
                    'unclear': '不明确',
                    'known': '已知',
                    'unknown': '未知',
                    'visible': '可见',
                    'invisible': '不可见',
                    'public': '公开',
                    'private': '私密',
                    'secret': '秘密',
                    'classified': '机密',
                    'top secret': '绝密',
                    'leaked': '泄露',
                    'exposed': '暴露',
                    'revealed': '揭示',
                    'disclosed': '披露',
                    'published': '发布',
                    'released': '发布',
                    'issued': '发布',
                    'distributed': '分发',
                    'circulated': '传阅',
                    'broadcast': '广播',
                    'streamed': '直播',
                    'uploaded': '上传',
                    'downloaded': '下载',
                    'shared': '分享',
                    'forwarded': '转发',
                    'retweeted': '转发',
                    'viral': '病毒式传播',
                    'trending': ' trending',
                    'popular': '热门',
                    'famous': '著名',
                    'notorious': '臭名昭著',
                    'infamous': ' infamous',
                    'controversial': '有争议',
                    'debatable': '可辩论',
                    'disputed': '有争议',
                    'questioned': '质疑',
                    'challenged': '挑战',
                    'opposed': '反对',
                    'supported': '支持',
                    'backed': '支持',
                    'endorsed': '认可',
                    'approved': '批准',
                    'accepted': '接受',
                    'rejected': '拒绝',
                    'denied': '否认',
                    'refused': '拒绝',
                    'declined': '拒绝',
                    'opposition': '反对',
                    'resistance': '抵抗',
                    'objection': '异议',
                    'complaint': '投诉',
                    'criticism': '批评',
                    'blame': '责备',
                    'accusation': '指控',
                    'allegation': '指控',
                    'charge': '指控',
                    'indictment': '起诉',
                    'prosecution': '起诉',
                    'trial': '审判',
                    'court': '法庭',
                    'judge': '法官',
                    'jury': '陪审团',
                    'verdict': '裁决',
                    'sentence': '判决',
                    'convicted': '定罪',
                    'acquitted': '无罪释放',
                    'guilty': '有罪',
                    'innocent': '无辜',
                    'evidence': '证据',
                    'proof': '证明',
                    'witness': '证人',
                    'testimony': '证词',
                    'confession': '供认',
                    'admission': '承认',
                    'denial': '否认',
                    'lie': '谎言',
                    'truth': '真相',
                    'fact': '事实',
                    'fiction': '虚构',
                    'rumor': '谣言',
                    'speculation': '猜测',
                    'theory': '理论',
                    'hypothesis': '假设',
                    'prediction': '预测',
                    'forecast': '预测',
                    'projection': '预测',
                    'estimate': '估计',
                    'calculation': '计算',
                    'analysis': '分析',
                    'assessment': '评估',
                    'evaluation': '评估',
                    'review': '审查',
                    'inspection': '检查',
                    'investigation': '调查',
                    'inquiry': '调查',
                    'probe': '调查',
                    'audit': '审计',
                    'survey': '调查',
                    'poll': '民调',
                    'study': '研究',
                    'research': '研究',
                    'report': '报告',
                    'paper': '论文',
                    'article': '文章',
                    'story': '报道',
                    'coverage': '报道',
                    'broadcast': '广播',
                    'transmission': '传输',
                    'signal': '信号',
                    'communication': '通讯',
                    'message': '消息',
                    'information': '信息',
                    'data': '数据',
                    'statistics': '统计',
                    'figures': '数字',
                    'numbers': '数字',
                    'amount': '数量',
                    'quantity': '数量',
                    'volume': '数量',
                    'level': '水平',
                    'rate': '率',
                    'percentage': '百分比',
                    'ratio': '比例',
                    'proportion': '比例',
                    'comparison': '比较',
                    'contrast': '对比',
                    'difference': '差异',
                    'similarity': '相似',
                    'change': '变化',
                    'increase': '增加',
                    'decrease': '减少',
                    'rise': '上升',
                    'fall': '下降',
                    'growth': '增长',
                    'decline': '下降',
                    'drop': '下降',
                    'jump': '跳升',
                    'surge': '激增',
                    'spike': '飙升',
                    'plunge': '暴跌',
                    'crash': '崩溃',
                    'collapse': '崩溃',
                    'boom': '繁荣',
                    'bust': '萧条',
                    'peak': '峰值',
                    'bottom': '谷底',
                    'record high': '历史新高',
                    'record low': '历史新低',
                    'all-time high': '历史新高',
                    'all-time low': '历史新低',
                    'maximum': '最大',
                    'minimum': '最小',
                    'average': '平均',
                    'median': '中位数',
                    'total': '总计',
                    'sum': '总和',
                    'cumulative': '累计',
                    'aggregate': '合计',
                    'overall': '总体',
                    'general': '一般',
                    'specific': '具体',
                    'particular': '特定',
                    'certain': '某些',
                    'various': '各种',
                    'multiple': '多个',
                    'numerous': '众多',
                    'many': '许多',
                    'few': '少数',
                    'several': '几个',
                    'some': '一些',
                    'all': '所有',
                    'none': '没有',
                    'both': '两者',
                    'either': '任一',
                    'neither': '两者都不',
                    'each': '每个',
                    'every': '每',
                    'any': '任何',
                    'other': '其他',
                    'another': '另一个',
                    'same': '相同',
                    'different': '不同',
                    'similar': '相似',
                    'identical': '相同',
                    'unique': '独特',
                    'distinct': '不同',
                    'separate': '分开',
                    'individual': '个体',
                    'personal': '个人',
                    'private': '私人',
                    'public': '公共',
                    'collective': '集体',
                    'joint': '联合',
                    'shared': '共享',
                    'mutual': '相互',
                    'common': '共同',
                    'universal': '普遍',
                    'global': '全球',
                    'worldwide': '全球',
                    'international': '国际',
                    'domestic': '国内',
                    'local': '本地',
                    'regional': '区域',
                    'national': '国家',
                    'federal': '联邦',
                    'state': '州',
                    'provincial': '省',
                    'municipal': '市',
                    'city': '城市',
                    'urban': '城市',
                    'rural': '农村',
                    'suburban': '郊区',
                    'residential': '住宅',
                    'commercial': '商业',
                    'industrial': '工业',
                    'agricultural': '农业',
                    'educational': '教育',
                    'medical': '医疗',
                    'military': '军事',
                    'civilian': '民用',
                    'official': '官方',
                    'unofficial': '非官方',
                    'formal': '正式',
                    'informal': '非正式',
                    'professional': '专业',
                    'amateur': '业余',
                    'expert': '专家',
                    'specialist': '专家',
                    'novice': '新手',
                    'beginner': '初学者',
                    'intermediate': '中级',
                    'advanced': '高级',
                    'master': '大师',
                    'chief': '首席',
                    'head': '负责人',
                    'director': '总监',
                    'manager': '经理',
                    'supervisor': '主管',
                    'coordinator': '协调员',
                    'officer': '官员',
                    'executive': '高管',
                    'administrator': '管理员',
                    'operator': '操作员',
                    'worker': '工人',
                    'staff': '员工',
                    'personnel': '人员',
                    'crew': '船员',
                    'team': '团队',
                    'group': '组',
                    'unit': '单位',
                    'division': '部门',
                    'department': '部门',
                    'section': '科室',
                    'branch': '分支',
                    'agency': '机构',
                    'bureau': '局',
                    'office': '办公室',
                    'center': '中心',
                    'institute': '研究所',
                    'academy': '学院',
                    'university': '大学',
                    'college': '学院',
                    'school': '学校',
                    'hospital': '医院',
                    'clinic': '诊所',
                    'laboratory': '实验室',
                    'library': '图书馆',
                    'museum': '博物馆',
                    'gallery': '画廊',
                    'theater': '剧院',
                    'stadium': '体育场',
                    'arena': '竞技场',
                    'park': '公园',
                    'garden': '花园',
                    'square': '广场',
                    'plaza': '广场',
                    'street': '街道',
                    'road': '道路',
                    'avenue': '大道',
                    'boulevard': '林荫大道',
                    'highway': '高速公路',
                    'expressway': '快速路',
                    'freeway': '高速公路',
                    'motorway': '高速公路',
                    'bridge': '桥梁',
                    'tunnel': '隧道',
                    'dam': '大坝',
                    'canal': '运河',
                    'reservoir': '水库',
                    'well': '井',
                    'mine': '矿井',
                    'quarry': '采石场',
                    'farm': '农场',
                    'ranch': '牧场',
                    'plantation': '种植园',
                    'orchard': '果园',
                    'vineyard': '葡萄园',
                    'field': '田地',
                    'meadow': '草地',
                    'pasture': '牧场',
                    'forest': '森林',
                    'wood': '树林',
                    'grove': '小树林',
                    'jungle': '丛林',
                    'rainforest': '雨林',
                    'savanna': '草原',
                    'tundra': '苔原',
                    'wetland': '湿地',
                    'marsh': '沼泽',
                    'swamp': '沼泽',
                    'bog': '泥炭沼',
                    'fen': '碱沼',
                    'reef': '礁',
                    'atoll': '环礁',
                    'archipelago': '群岛',
                    'chain': '链',
                    'range': '山脉',
                    'ridge': '山脊',
                    'peak': '山峰',
                    'summit': '山顶',
                    'crest': ' crest',
                    'slope': ' slope',
                    'hillside': ' hillside',
                    'cliff': '悬崖',
                    'bluff': ' bluff',
                    'crag': ' crag',
                    'outcrop': ' outcrop',
                    'boulder': '巨石',
                    'rock': '岩石',
                    'stone': '石头',
                    'pebble': '鹅卵石',
                    'gravel': '砾石',
                    'sand': '沙子',
                    'soil': '土壤',
                    'dirt': '泥土',
                    'mud': '泥浆',
                    'clay': '粘土',
                    'silt': '淤泥',
                    'sediment': '沉积物',
                    'deposit': '沉积',
                    'layer': '层',
                    'bed': '床',
                    'stratum': '地层',
                    'formation': '构造',
                    'structure': '结构',
                    'feature': '特征',
                    'landmark': '地标',
                    'monument': '纪念碑',
                    'memorial': '纪念馆',
                    'statue': '雕像',
                    'sculpture': '雕塑',
                    'fountain': '喷泉',
                    'tower': '塔',
                    'spire': '尖塔',
                    'dome': '圆顶',
                    'minaret': '尖塔',
                    'pagoda': '宝塔',
                    'temple': '寺庙',
                    'church': '教堂',
                    'cathedral': '大教堂',
                    'mosque': '清真寺',
                    'synagogue': '犹太教堂',
                    'shrine': '神龛',
                    'altar': '祭坛',
                    'sanctuary': '圣地',
                    'holy': '神圣',
                    'sacred': '神圣',
                    'religious': '宗教',
                    'spiritual': '精神',
                    'divine': '神圣',
                    'blessed': '祝福',
                    'cursed': '诅咒',
                    'evil': '邪恶',
                    'wicked': '邪恶',
                    'sinful': '有罪',
                    'immoral': '不道德',
                    'unethical': '不道德',
                    'illegal': '非法',
                    'unlawful': '非法',
                    'legitimate': '合法',
                    'valid': '有效',
                    'invalid': '无效',
                    'void': '无效',
                    'null': '空',
                    'empty': '空',
                    'full': '满',
                    'complete': '完整',
                    'incomplete': '不完整',
                    'partial': '部分',
                    'whole': '整体',
                    'entire': '整个',
                    'total': '总计',
                    'absolute': '绝对',
                    'relative': '相对',
                    'positive': '积极',
                    'negative': '消极',
                    'neutral': '中立',
                    'objective': '客观',
                    'subjective': '主观',
                    'biased': '偏见',
                    'unbiased': '无偏见',
                    'fair': '公平',
                    'unfair': '不公平',
                    'just': '公正',
                    'unjust': '不公正',
                    'equal': '平等',
                    'unequal': '不平等',
                    'same': '相同',
                    'different': '不同',
                    'identical': '相同',
                    'distinct': '不同',
                    'unique': '独特',
                    'rare': '罕见',
                    'common': '常见',
                    'frequent': '频繁',
                    'regular': '定期',
                    'irregular': '不定期',
                    'normal': '正常',
                    'abnormal': '异常',
                    'standard': '标准',
                    'non-standard': '非标准',
                    'typical': '典型',
                    'atypical': '非典型',
                    'usual': '通常',
                    'unusual': '不寻常',
                    'ordinary': '普通',
                    'extraordinary': '非凡',
                    'remarkable': '显著',
                    'notable': '值得注意',
                    'noticeable': '明显',
                    'obvious': '明显',
                    'apparent': '明显',
                    'evident': '明显',
                    'clear': '清楚',
                    'unclear': '不清楚',
                    'ambiguous': '模糊',
                    'vague': '含糊',
                    'precise': '精确',
                    'exact': '准确',
                    'accurate': '准确',
                    'inaccurate': '不准确',
                    'correct': '正确',
                    'incorrect': '不正确',
                    'right': '正确',
                    'wrong': '错误',
                    'true': '真实',
                    'false': '虚假',
                    'real': '真实',
                    'fake': '虚假',
                    'genuine': '真实',
                    'authentic': '真实',
                    'original': '原始',
                    'copy': '副本',
                    'replica': '复制品',
                    'duplicate': '副本',
                    'clone': '克隆',
                    'imitation': '仿制品',
                    'simulation': '模拟',
                    'model': '模型',
                    'sample': '样本',
                    'example': '例子',
                    'instance': '实例',
                    'case': '案例',
                    'situation': '情况',
                    'scenario': '场景',
                    'context': '背景',
                    'background': '背景',
                    'history': '历史',
                    'past': '过去',
                    'present': '现在',
                    'future': '未来',
                    'current': '当前',
                    'former': '前任',
                    'previous': '以前',
                    'next': '下一个',
                    'following': '以下',
                    'subsequent': '随后',
                    'prior': '之前',
                    'preceding': ' preceding',
                    'above': '以上',
                    'below': '以下',
                    'over': '超过',
                    'under': '低于',
                    'beyond': '超出',
                    'within': '之内',
                    'inside': '内部',
                    'outside': '外部',
                    'inner': '内部',
                    'outer': '外部',
                    'exterior': '外部',
                    'interior': '内部',
                    'surface': '表面',
                    'depth': '深度',
                    'height': '高度',
                    'width': '宽度',
                    'length': '长度',
                    'size': '尺寸',
                    'scale': '规模',
                    'scope': '范围',
                    'range': '范围',
                    'extent': '程度',
                    'degree': '程度',
                    'magnitude': '量级',
                    'intensity': '强度',
                    'strength': '强度',
                    'power': '力量',
                    'force': '力',
                    'energy': '能量',
                    'pressure': '压力',
                    'stress': '压力',
                    'strain': '应变',
                    'tension': '张力',
                    'compression': '压缩',
                    'expansion': '膨胀',
                    'contraction': '收缩',
                    'growth': '增长',
                    'shrinkage': '收缩',
                    'stretch': '拉伸',
                    'squeeze': '挤压',
                    'twist': '扭曲',
                    'bend': '弯曲',
                    'fold': '折叠',
                    'unfold': '展开',
                    'wrap': '包裹',
                    'unwrap': '打开',
                    'cover': '覆盖',
                    'uncover': '揭开',
                    'hide': '隐藏',
                    'reveal': '揭示',
                    'show': '显示',
                    'display': '展示',
                    'exhibit': '展览',
                    'demonstrate': '演示',
                    'illustrate': '说明',
                    'explain': '解释',
                    'describe': '描述',
                    'depict': '描绘',
                    'portray': '描绘',
                    'represent': '代表',
                    'symbolize': '象征',
                    'signify': '表示',
                    'mean': '意思是',
                    'indicate': '表明',
                    'suggest': '建议',
                    'imply': '暗示',
                    'hint': '暗示',
                    'clue': '线索',
                    'evidence': '证据',
                    'proof': '证明',
                    'sign': '迹象',
                    'signal': '信号',
                    'mark': '标记',
                    'symbol': '符号',
                    'logo': '标志',
                    'brand': '品牌',
                    'trademark': '商标',
                    'label': '标签',
                    'tag': '标签',
                    'flag': '旗帜',
                    'banner': '横幅',
                    'poster': '海报',
                    'billboard': '广告牌',
                    'signboard': '招牌',
                    'placard': '标语牌',
                    'notice': '通知',
                    'announcement': '公告',
                    'bulletin': '公告',
                    'circular': '通告',
                    'leaflet': '传单',
                    'flyer': '传单',
                    'brochure': '手册',
                    'pamphlet': '小册子',
                    'booklet': '小册子',
                    'book': '书',
                    'magazine': '杂志',
                    'journal': '期刊',
                    'periodical': '期刊',
                    'newspaper': '报纸',
                    'gazette': '公报',
                    'newsletter': '通讯',
                    'report': '报告',
                    'document': '文件',
                    'file': '文件',
                    'record': '记录',
                    'archive': '档案',
                    'database': '数据库',
                    'dataset': '数据集',
                    'collection': '集合',
                    'compilation': '汇编',
                    'catalog': '目录',
                    'directory': '目录',
                    'index': '索引',
                    'list': '列表',
                    'inventory': '清单',
                    'register': '登记',
                    'roll': '名册',
                    'roster': '名单',
                    'schedule': '日程',
                    'timetable': '时刻表',
                    'calendar': '日历',
                    'agenda': '议程',
                    'itinerary': '行程',
                    'plan': '计划',
                    'program': '程序',
                    'project': '项目',
                    'scheme': '方案',
                    'proposal': '建议',
                    'proposition': '提议',
                    'motion': '动议',
                    'resolution': '决议',
                    'decision': '决定',
                    'determination': '决心',
                    'conclusion': '结论',
                    'finding': '发现',
                    'discovery': '发现',
                    'invention': '发明',
                    'innovation': '创新',
                    'creation': '创造',
                    'production': '生产',
                    'manufacture': '制造',
                    'construction': '建设',
                    'building': '建筑',
                    'architecture': '建筑',
                    'design': '设计',
                    'pattern': '图案',
                    'model': '模型',
                    'prototype': '原型',
                    'sample': '样品',
                    'specimen': '标本',
                    'copy': '副本',
                    'version': '版本',
                    'edition': '版',
                    'variation': '变体',
                    'variant': '变体',
                    'type': '类型',
                    'kind': '种类',
                    'sort': '种类',
                    'class': '类别',
                    'category': '类别',
                    'group': '组',
                    'set': '集合',
                    'series': '系列',
                    'sequence': '序列',
                    'chain': '链',
                    'string': '字符串',
                    'array': '数组',
                    'matrix': '矩阵',
                    'grid': '网格',
                    'network': '网络',
                    'web': '网络',
                    'mesh': '网',
                    'net': '网',
                    'trap': '陷阱',
                    'snare': '圈套',
                    'ambush': '伏击',
                    'surprise attack': '突袭',
                    'sneak attack': '偷袭',
                    'preventive strike': '先发制人',
                    'preemptive strike': '先发制人',
                    'first strike': '第一次打击',
                    'second strike': '第二次打击',
                    'counterattack': '反击',
                    'retaliation': '报复',
                    'revenge': '复仇',
                    'reprisal': '报复',
                    'retribution': '报应',
                    'punishment': '惩罚',
                    'penalty': '处罚',
                    'sanction': '制裁',
                    'fine': '罚款',
                    'fee': '费用',
                    'charge': '收费',
                    'cost': '成本',
                    'price': '价格',
                    'rate': '费率',
                    'tariff': '关税',
                    'tax': '税',
                    'duty': '关税',
                    'levy': '征收费',
                    'imposition': '征收',
                    'collection': '收集',
                    'payment': '支付',
                    'reimbursement': '报销',
                    'compensation': '补偿',
                    'reparation': '赔偿',
                    'damages': '损害赔偿',
                    'indemnity': '赔偿',
                    'insurance': '保险',
                    'premium': '保费',
                    'coverage': '保险范围',
                    'policy': '保单',
                    'claim': '索赔',
                    'settlement': '和解',
                    'award': '裁决',
                    'judgment': '判决',
                    'ruling': '裁决',
                    'order': '命令',
                    'decree': '法令',
                    'directive': '指令',
                    'instruction': '指示',
                    'command': '命令',
                    'mandate': '授权',
                    'authority': '权威',
                    'authorization': '授权',
                    'permission': '许可',
                    'consent': '同意',
                    'approval': '批准',
                    'clearance': '许可',
                    'license': '执照',
                    'permit': '许可证',
                    'warrant': '令状',
                    'writ': '书面命令',
                    'summons': '传票',
                    'subpoena': '传票',
                    'court order': '法庭命令',
                    'restraining order': '限制令',
                    'injunction': '禁令',
                    'cease and desist': '停止令',
                    'eviction notice': '驱逐通知',
                    'foreclosure': '止赎',
                    'repossession': '收回',
                    'confiscation': '没收',
                    'seizure': '扣押',
                    'forfeiture': ' forfeiture',
                    'surrender': '投降',
                    'yield': '屈服',
                    'submit': '提交',
                    'comply': '遵守',
                    'obey': '服从',
                    'follow': '跟随',
                    'observe': '观察',
                    'respect': '尊重',
                    'honor': '荣誉',
                    'dignity': '尊严',
                    'pride': '骄傲',
                    'shame': '羞耻',
                    'humiliation': '羞辱',
                    'embarrassment': '尴尬',
                    'disgrace': '耻辱',
                    'scandal': '丑闻',
                    'controversy': '争议',
                    'dispute': '争议',
                    'conflict': '冲突',
                    'clash': '冲突',
                    'collision': '碰撞',
                    'crash': '崩溃',
                    'accident': '事故',
                    'incident': '事件',
                    'event': '事件',
                    'occurrence': '发生',
                    'happening': '发生',
                    'phenomenon': '现象',
                    'situation': '情况',
                    'condition': '条件',
                    'state': '状态',
                    'status': '状态',
                    'position': '位置',
                    'location': '位置',
                    'place': '地方',
                    'spot': '地点',
                    'site': '地点',
                    'point': '点',
                    'area': '区域',
                    'zone': '区域',
                    'region': '地区',
                    'sector': '部门',
                    'section': '部分',
                    'segment': '片段',
                    'portion': '部分',
                    'part': '部分',
                    'piece': '件',
                    'bit': '位',
                    'item': '项目',
                    'article': '文章',
                    'object': '对象',
                    'thing': '东西',
                    'stuff': '东西',
                    'material': '材料',
                    'substance': '物质',
                    'matter': '物质',
                    'element': '元素',
                    'component': '组件',
                    'constituent': '成分',
                    'ingredient': '成分',
                    'factor': '因素',
                    'aspect': '方面',
                    'facet': '方面',
                    'dimension': '维度',
                    'perspective': '视角',
                    'viewpoint': '观点',
                    'standpoint': '立场',
                    'angle': '角度',
                    'approach': '方法',
                    'method': '方法',
                    'technique': '技术',
                    'strategy': '策略',
                    'tactic': '战术',
                    'plan': '计划',
                    'scheme': '方案',
                    'plot': '情节',
                    'conspiracy': '阴谋',
                    'intrigue': '阴谋',
                    'machination': '阴谋',
                    'maneuver': '机动',
                    'operation': '操作',
                    'exercise': '演习',
                    'maneuver': '演习',
                    'drill': '演习',
                    'practice': '练习',
                    'rehearsal': '彩排',
                    'preparation': '准备',
                    'readiness': '准备就绪',
                    'alert': '警戒',
                    'standby': '待命',
                    'waiting': '等待',
                    'pending': '待定',
                    'outstanding': '未决',
                    'unsettled': '未解决',
                    'resolved': '已解决',
                    'settled': '已解决',
                    'closed': '已关闭',
                    'concluded': '已结束',
                    'finished': '已完成',
                    'completed': '已完成',
                    'done': '完成',
                    'over': '结束',
                    'ended': '结束',
                    'terminated': '终止',
                    'ceased': '停止',
                    'stopped': '停止',
                    'halted': '停止',
                    'suspended': '暂停',
                    'interrupted': '中断',
                    'disrupted': '中断',
                    'disturbed': '干扰',
                    'interfered': '干涉',
                    'prevented': '阻止',
                    'blocked': '阻止',
                    'hindered': '阻碍',
                    'hampered': '妨碍',
                    'impeded': '阻碍',
                    'obstructed': '阻碍',
                    'barred': '禁止',
                    'banned': '禁止',
                    'prohibited': '禁止',
                    'forbidden': '禁止',
                    'outlawed': '取缔',
                    'illegal': '非法',
                    'unlawful': '非法',
                    'illegitimate': '非法',
                    'illicit': '非法',
                    'criminal': '犯罪',
                    'felony': '重罪',
                    'misdemeanor': '轻罪',
                    'offense': '犯罪',
                    'crime': '犯罪',
                    'sin': '罪恶',
                    'vice': '恶习',
                    'corruption': '腐败',
                    'bribery': '贿赂',
                    'extortion': '勒索',
                    'fraud': '欺诈',
                    'deception': '欺骗',
                    'cheating': '作弊',
                    'trickery': '诡计',
                    'hoax': '骗局',
                    'scam': '诈骗',
                    'con': '诈骗',
                    'swindle': '诈骗',
                    'embezzlement': '挪用公款',
                    'theft': '盗窃',
                    'robbery': '抢劫',
                    'burglary': '入室盗窃',
                    'larceny': '盗窃罪',
                    'shoplifting': ' shoplifting',
                    'pickpocketing': '扒窃',
                    'mugging': '抢劫',
                    'hold-up': '持械抢劫',
                    'heist': '盗窃',
                    'raid': '突袭',
                    'break-in': '闯入',
                    'trespass': ' trespass',
                    'intrusion': '入侵',
                    'invasion': '入侵',
                    'infiltration': '渗透',
                    'penetration': '渗透',
                    'breach': '违反',
                    'violation': '违反',
                    'infringement': '侵权',
                    'transgression': '越轨',
                    'offense': '冒犯',
                    'wrongdoing': '不当行为',
                    'misconduct': '不当行为',
                    'misbehavior': '不良行为',
                    'malpractice': '渎职',
                    'negligence': '疏忽',
                    'carelessness': '粗心',
                    'recklessness': '鲁莽',
                    'rashness': '轻率',
                    'impulsiveness': '冲动',
                    'aggression': '侵略',
                    'hostility': '敌意',
                    'animosity': '敌意',
                    'enmity': '敌意',
                    'hatred': '仇恨',
                    'loathing': '厌恶',
                    'detestation': '憎恶',
                    'abhorrence': '憎恶',
                    'revulsion': '反感',
                    'repulsion': '厌恶',
                    'disgust': '厌恶',
                    'distaste': '反感',
                    'aversion': '厌恶',
                    'antipathy': '反感',
                    'dislike': '不喜欢',
                    'dissatisfaction': '不满',
                    'discontent': '不满',
                    'displeasure': '不悦',
                    'annoyance': '烦恼',
                    'irritation': '恼怒',
                    'anger': '愤怒',
                    'rage': '暴怒',
                    'fury': '狂怒',
                    'wrath': '愤怒',
                    'ire': '愤怒',
                    'indignation': '愤慨',
                    'resentment': '怨恨',
                    'bitterness': '痛苦',
                    'acrimony': '尖刻',
                    'rancor': '怨恨',
                    'malice': '恶意',
                    'spite': '恶意',
                    'venom': '毒液',
                    'poison': '毒药',
                    'toxin': '毒素',
                    'contaminant': '污染物',
                    'pollutant': '污染物',
                    'impurity': '杂质',
                    'adulterant': '掺杂物',
                    'additive': '添加剂',
                    'preservative': '防腐剂',
                    'antioxidant': '抗氧化剂',
                    'antibiotic': '抗生素',
                    'antiviral': '抗病毒',
                    'antifungal': '抗真菌',
                    'antiseptic': '防腐剂',
                    'disinfectant': '消毒剂',
                    'sterilizer': '杀菌剂',
                    'sanitizer': '消毒剂',
                    'cleaner': '清洁剂',
                    'detergent': '洗涤剂',
                    'soap': '肥皂',
                    'shampoo': '洗发水',
                    'conditioner': '护发素',
                    'lotion': '乳液',
                    'cream': '霜',
                    'ointment': '软膏',
                    'salve': '药膏',
                    'balm': '香膏',
                    'poultice': '泥敷剂',
                    'compress': '敷布',
                    'bandage': '绷带',
                    'dressing': '敷料',
                    'plaster': '膏药',
                    'tape': '胶带',
                    'gauze': '纱布',
                    'cotton': '棉花',
                    'pad': '垫',
                    'swab': '棉签',
                    'wipe': '湿巾',
                    'tissue': '纸巾',
                    'napkin': '餐巾',
                    'towel': '毛巾',
                    'cloth': '布',
                    'fabric': '织物',
                    'textile': '纺织品',
                    'material': '材料',
                    'fiber': '纤维',
                    'thread': '线',
                    'yarn': '纱线',
                    'string': '绳子',
                    'cord': '绳索',
                    'rope': '绳索',
                    'cable': '电缆',
                    'wire': '电线',
                    'line': '线',
                    'chain': '链条',
                    'link': '链接',
                    'connection': '连接',
                    'junction': '连接点',
                    'intersection': '交叉口',
                    'crossing': '十字路口',
                    'crossroads': '十字路口',
                    'fork': '岔路口',
                    'turning': '转弯处',
                    'bend': '弯道',
                    'curve': '曲线',
                    'arc': '弧线',
                    'circle': '圆',
                    'loop': '环',
                    'ring': '环',
                    'hoop': '箍',
                    'band': '带',
                    'strip': '条',
                    'stripe': '条纹',
                    'line': '线',
                    'bar': '条',
                    'rod': '杆',
                    'pole': '杆',
                    'post': '柱',
                    'pillar': '柱子',
                    'column': '柱',
                    'beam': '梁',
                    'girder': '大梁',
                    'joist': '托梁',
                    'rafter': '椽子',
                    'truss': '桁架',
                    'frame': '框架',
                    'structure': '结构',
                    'construction': '建设',
                    'edifice': '大厦',
                    'building': '建筑',
                    'house': '房子',
                    'home': '家',
                    'residence': '住宅',
                    'dwelling': '住所',
                    'habitation': '居住地',
                    'abode': '住所',
                    'domicile': '户籍',
                    'property': '财产',
                    'estate': '房地产',
                    'real estate': '房地产',
                    'land': '土地',
                    'ground': '地面',
                    'earth': '地球',
                    'soil': '土壤',
                    'terrain': '地形',
                    'topography': '地形',
                    'landscape': '风景',
                    'scenery': '风景',
                    'view': '景色',
                    'vista': '远景',
                    'panorama': '全景',
                    'outlook': '前景',
                    'prospect': '前景',
                    'perspective': '视角',
                    'angle': '角度',
                    'aspect': '方面',
                    'facet': '方面',
                    'side': '边',
                    'face': '面',
                    'surface': '表面',
                    'front': '前面',
                    'back': '后面',
                    'rear': '后方',
                    'top': '顶部',
                    'bottom': '底部',
                    'upper': '上部',
                    'lower': '下部',
                    'higher': '更高',
                    'lower': '更低',
                    'superior': '上级',
                    'inferior': '下级',
                    'senior': '高级',
                    'junior': '初级',
                    'elder': '长辈',
                    'younger': '年幼',
                    'older': '年长',
                    'newer': '较新',
                    'ancient': '古代',
                    'old': '老',
                    'modern': '现代',
                    'contemporary': '当代',
                    'current': '当前',
                    'recent': '最近',
                    'latest': '最新',
                    'new': '新',
                    'fresh': '新鲜',
                    'novel': '新颖',
                    'original': '原始',
                    'creative': '创意',
                    'innovative': '创新',
                    'inventive': '发明',
                    'imaginative': '富有想象力',
                    'fanciful': '异想天开',
                    'fantastic': '奇妙',
                    'fabulous': '极好',
                    'wonderful': '精彩',
                    'marvelous': '不可思议',
                    'magnificent': '宏伟',
                    'splendid': '辉煌',
                    'glorious': '光荣',
                    'grand': '盛大',
                    'impressive': '令人印象深刻',
                    'striking': '惊人',
                    'remarkable': '显著',
                    'notable': '值得注意',
                    'noteworthy': '值得注意',
                    'significant': '重要',
                    'important': '重要',
                    'major': '主要',
                    'main': '主要',
                    'principal': '主要',
                    'primary': '主要',
                    'chief': '首席',
                    'key': '关键',
                    'central': '中心',
                    'core': '核心',
                    'essential': '必要',
                    'vital': '至关重要',
                    'critical': '关键',
                    'crucial': '至关重要',
                    'pivotal': '关键',
                    'decisive': '决定性',
                    'conclusive': '决定性',
                    'final': '最终',
                    'ultimate': '最终',
                    'eventual': '最终',
                    'last': '最后',
                    'latest': '最新',
                    'recent': '最近',
                    'current': '当前',
                    'present': '现在',
                    'existing': '现有',
                    'actual': '实际',
                    'real': '真实',
                    'true': '真实',
                    'genuine': '真实',
                    'authentic': '真实',
                    'legitimate': '合法',
                    'valid': '有效',
                    'sound': '合理',
                    'solid': '稳固',
                    'strong': '强大',
                    'powerful': '强大',
                    'mighty': '强大',
                    'potent': '有力',
                    'forceful': '有力',
                    'vigorous': '有力',
                    'energetic': '精力充沛',
                    'dynamic': '动态',
                    'active': '活跃',
                    'lively': '活泼',
                    'vivid': '生动',
                    'vibrant': '充满活力',
                    'colorful': '多彩',
                    'bright': '明亮',
                    'brilliant': '辉煌',
                    'radiant': '光芒四射',
                    'shining': '闪耀',
                    'glowing': '发光',
                    'gleaming': '闪烁',
                    'glistening': '闪光',
                    'sparkling': '闪闪发光',
                    'glittering': '闪闪发光',
                    'twinkling': '闪烁',
                    'flickering': '闪烁',
                    'flashing': '闪光',
                    'blinking': '眨眼',
                    'winking': '眨眼',
                    'nodding': '点头',
                    'shaking': '摇晃',
                    'waving': '挥手',
                    'swinging': '摆动',
                    'swaying': '摇摆',
                    'rocking': '摇晃',
                    'rolling': '滚动',
                    'turning': '转动',
                    'rotating': '旋转',
                    'spinning': '旋转',
                    'whirling': '旋转',
                    'twirling': '旋转',
                    'swirling': '漩涡',
                    'circling': '盘旋',
                    'orbiting': '轨道',
                    'revolving': '旋转',
                    'rotating': '旋转',
                    'pivoting': ' pivot',
                    'swiveling': '旋转',
                    'twisting': '扭曲',
                    'winding': '缠绕',
                    'coiling': '盘绕',
                    'curling': '卷曲',
                    'bending': '弯曲',
                    'flexing': ' flex',
                    'stretching': '拉伸',
                    'extending': '延伸',
                    'reaching': '到达',
                    'spreading': '传播',
                    'expanding': '扩展',
                    'growing': '增长',
                    'increasing': '增加',
                    'rising': '上升',
                    'climbing': '攀登',
                    'ascending': '上升',
                    'mounting': ' mount',
                    'scaling': ' scaling',
                    'surging': '激增',
                    'soaring': ' soaring',
                    'skyrocketing': '飞涨',
                    'spiking': '飙升',
                    'peaking': '达到峰值',
                    'cresting': ' crest',
                    'topping': ' topping',
                    'maximizing': '最大化',
                    'optimizing': '优化',
                    'improving': '改进',
                    'enhancing': '增强',
                    'boosting': '提升',
                    'upgrading': '升级',
                    'advancing': '推进',
                    'progressing': '进步',
                    'developing': '发展',
                    'evolving': '进化',
                    'transforming': '转变',
                    'changing': '改变',
                    'converting': '转换',
                    'transforming': '转换',
                    'translating': '翻译',
                    'interpreting': '解释',
                    'explaining': '说明',
                    'clarifying': '澄清',
                    'illuminating': '阐明',
                    'elucidating': '阐明',
                    'demonstrating': '演示',
                    'proving': '证明',
                    'verifying': '验证',
                    'confirming': '确认',
                    'validating': '验证',
                    'authenticating': '认证',
                    'certifying': '认证',
                    'guaranteeing': '保证',
                    'ensuring': '确保',
                    'assuring': '保证',
                    'securing': '保护',
                    'protecting': '保护',
                    'defending': '保卫',
                    'guarding': '守卫',
                    'shielding': '屏蔽',
                    'sheltering': '庇护',
                    'harboring': ' harbor',
                    'housing': ' housing',
                    'accommodating': ' accommodate',
                    'lodging': ' lodging',
                    'boarding': ' boarding',
                    'feeding': '喂养',
                    'nourishing': '滋养',
                    'nurturing': '培育',
                    'cultivating': '培养',
                    'fostering': ' foster',
                    'promoting': '促进',
                    'encouraging': '鼓励',
                    'supporting': '支持',
                    'backing': '支持',
                    'helping': '帮助',
                    'aiding': '援助',
                    'assisting': '协助',
                    'serving': '服务',
                    'attending': '参加',
                    'tending': '照料',
                    'caring': '关心',
                    'loving': '爱',
                    'liking': '喜欢',
                    'enjoying': '享受',
                    'appreciating': '欣赏',
                    'valuing': '重视',
                    'treasuring': '珍惜',
                    'cherishing': '珍爱',
                    'prizing': '珍视',
                    'esteeming': '尊重',
                    'respecting': '尊重',
                    'honoring': '尊敬',
                    'revering': '崇敬',
                    'worshiping': '崇拜',
                    'adoring': '崇拜',
                    'admiring': '钦佩',
                    'looking up to': '敬仰',
                    'idolizing': ' idolize',
                    'idealizing': ' idealize',
                    'romanticizing': ' romanticize',
                    'fantasizing': '幻想',
                    'dreaming': '做梦',
                    'imagining': '想象',
                    'envisioning': '设想',
                    'visualizing': '可视化',
                    'picturing': '想象',
                    'conceiving': '构思',
                    'conceptualizing': '概念化',
                    'theorizing': '理论化',
                    'hypothesizing': '假设',
                    'speculating': '推测',
                    'guessing': '猜测',
                    'estimating': '估计',
                    'calculating': '计算',
                    'computing': '计算',
                    'processing': '处理',
                    'analyzing': '分析',
                    'examining': '检查',
                    'inspecting': '检查',
                    'investigating': '调查',
                    'studying': '研究',
                    'researching': '研究',
                    'exploring': '探索',
                    'discovering': '发现',
                    'finding': '发现',
                    'detecting': '检测',
                    'sensing': '感知',
                    'feeling': '感觉',
                    'perceiving': '感知',
                    'noticing': '注意',
                    'observing': '观察',
                    'watching': '观看',
                    'viewing': '查看',
                    'seeing': '看见',
                    'looking': '看',
                    'gazing': '凝视',
                    'staring': '盯着',
                    'glancing': '瞥',
                    'peeking': '偷看',
                    'peering': '窥视',
                    'scanning': '扫描',
                    'surveying': '调查',
                    'monitoring': '监控',
                    'tracking': '追踪',
                    'following': '跟随',
                    'pursuing': '追求',
                    'chasing': '追逐',
                    'hunting': '狩猎',
                    'searching': '搜索',
                    'seeking': '寻求',
                    'questing': '探索',
                    'exploring': '探索',
                    'prospecting': '勘探',
                    'mining': '采矿',
                    'excavating': '挖掘',
                    'digging': '挖掘',
                    'unearthing': '发掘',
                    'exhuming': '挖掘',
                    'disinterring': '掘出',
                    'resurrecting': '复活',
                    'reviving': '复兴',
                    'restoring': '恢复',
                    'recovering': '恢复',
                    'retrieving': '取回',
                    'reclaiming': '回收',
                    'recycling': '回收',
                    'reusing': '再利用',
                    'repurposing': '改作他用',
                    'refurbishing': '翻新',
                    'renovating': '翻新',
                    'remodeling': '改造',
                    'reconstructing': '重建',
                    'rebuilding': '重建',
                    'reassembling': '重新组装',
                    'reorganizing': '重组',
                    'restructuring': '重组',
                    'reforming': '改革',
                    'transforming': '改革',
                    'revolutionizing': '革命',
                    'overthrowing': '推翻',
                    'toppling': '推翻',
                    'deposing': '废黜',
                    'dethroning': '废黜',
                    'ousting': '罢免',
                    'ejecting': '驱逐',
                    'expelling': '驱逐',
                    'banishing': '流放',
                    'exiling': '流放',
                    'deporting': '驱逐出境',
                    'extraditing': '引渡',
                    'surrendering': '投降',
                    'yielding': '屈服',
                    'submitting': '提交',
                    'succumbing': '屈服',
                    'capitulating': '投降',
                    'giving in': '屈服',
                    'giving up': '放弃',
                    'quitting': '退出',
                    'resigning': '辞职',
                    'retiring': '退休',
                    'stepping down': '下台',
                    'abdicating': '退位',
                    'renouncing': '放弃',
                    'waiving': '放弃',
                    'forfeiting': '放弃',
                    'sacrificing': '牺牲',
                    'giving': '给予',
                    'donating': '捐赠',
                    'contributing': '贡献',
                    'offering': '提供',
                    'presenting': '呈现',
                    'delivering': '交付',
                    'handing': '递交',
                    'transferring': '转移',
                    'conveying': '传达',
                    'transmitting': '传输',
                    'sending': '发送',
                    'dispatching': '派遣',
                    'shipping': '运送',
                    'transporting': '运输',
                    'moving': '移动',
                    'shifting': '转移',
                    'relocating': '迁移',
                    'resettling': '重新定居',
                    'migrating': '迁移',
                    'emigrating': '移居',
                    'immigrating': '移民',
                    'traveling': '旅行',
                    'journeying': '旅行',
                    'voyaging': '航行',
                    'sailing': '航行',
                    'cruising': '巡航',
                    'flying': '飞行',
                    'piloting': '驾驶',
                    'navigating': '导航',
                    'steering': '掌舵',
                    'driving': '驾驶',
                    'riding': '骑',
                    'cycling': '骑自行车',
                    'walking': '步行',
                    'hiking': '徒步',
                    'trekking': '长途跋涉',
                    'marching': '行军',
                    'parading': '游行',
                    'processing': ' procession',
                    'demonstrating': '示威',
                    'protesting': '抗议',
                    'rallying': '集会',
                    'assembling': '组装',
                    'gathering': '聚集',
                    'collecting': '收集',
                    'accumulating': '积累',
                    'amassing': '积聚',
                    'aggregating': '聚合',
                    'consolidating': '整合',
                    'integrating': '整合',
                    'unifying': '统一',
                    'merging': '合并',
                    'combining': '结合',
                    'joining': '加入',
                    'linking': '链接',
                    'connecting': '连接',
                    'coupling': '耦合',
                    'pairing': '配对',
                    'matching': '匹配',
                    'mating': '交配',
                    'breeding': '繁殖',
                    'reproducing': '繁殖',
                    'multiplying': '倍增',
                    'proliferating': '激增',
                    'spreading': '传播',
                    'diffusing': '扩散',
                    'dispersing': '分散',
                    'scattering': '散开',
                    'distributing': '分配',
                    'allocating': '分配',
                    'assigning': '分配',
                    'apportioning': '分摊',
                    'rationing': '配给',
                    'sharing': '分享',
                    'dividing': '分割',
                    'splitting': '分裂',
                    'separating': '分离',
                    'parting': '分开',
                    'detaching': '分离',
                    'disconnecting': '断开',
                    'unlinking': '取消链接',
                    'decoupling': '解耦',
                    'disengaging': '脱离',
                    'withdrawing': '撤回',
                    'removing': '移除',
                    'extracting': '提取',
                    'pulling': '拉',
                    'drawing': '拉',
                    'dragging': '拖',
                    'hauling': '拖',
                    'towing': '拖',
                    'tugging': ' tug',
                    'yanking': ' yank',
                    'jerking': ' jerk',
                    'twitching': ' twitch',
                    'fluttering': ' flutter',
                    'flapping': ' flapping',
                    'waving': '挥动',
                    'swaying': '摇摆',
                    'swinging': '摆动',
                    'rocking': '摇晃',
                    'shaking': '摇晃',
                    'trembling': '颤抖',
                    'shivering': '颤抖',
                    'quivering': '颤抖',
                    'vibrating': '振动',
                    'oscillating': '振荡',
                    'pulsating': '脉动',
                    'throbbing': '跳动',
                    'beating': '跳动',
                    'pounding': ' pounding',
                    'thumping': '砰砰',
                    'knocking': '敲门',
                    'tapping': '轻敲',
                    'rapping': '敲击',
                    'patting': '轻拍',
                    'stroking': '抚摸',
                    'caressing': '爱抚',
                    'fondling': ' fondle',
                    'petting': ' pet',
                    'cuddling': '拥抱',
                    'hugging': '拥抱',
                    'embracing': '拥抱',
                    'holding': '持有',
                    'grasping': '抓住',
                    'gripping': '握紧',
                    'clutching': ' clutch',
                    'clinging': ' cling',
                    'hanging': '悬挂',
                    'dangling': '悬挂',
                    'suspending': '暂停',
                    'hanging': '悬挂',
                    'pending': '待定',
                    'waiting': '等待',
                    'awaiting': '等待',
                    'expecting': '期待',
                    'anticipating': '预期',
                    'foreseeing': '预见',
                    'predicting': '预测',
                    'forecasting': '预报',
                    'projecting': '预计',
                    'estimating': '估计',
                    'calculating': '计算',
                    'reckoning': '估计',
                    'figuring': ' figuring',
                    'counting': '计数',
                    'numbering': '编号',
                    'enumerating': '列举',
                    'listing': '列出',
                    'itemizing': ' itemize',
                    'detailing': '详细说明',
                    'specifying': '指定',
                    'stipulating': '规定',
                    'prescribing': '规定',
                    'dictating': '命令',
                    'ordering': '命令',
                    'commanding': '命令',
                    'directing': '指导',
                    'instructing': '指示',
                    'guiding': '指导',
                    'leading': '领导',
                    'conducting': '进行',
                    'managing': '管理',
                    'handling': '处理',
                    'dealing': '处理',
                    'coping': '应对',
                    'grappling': '努力解决',
                    'struggling': '挣扎',
                    'striving': '努力',
                    'endeavoring': '努力',
                    'trying': '尝试',
                    'attempting': '试图',
                    'aiming': '旨在',
                    'intending': '打算',
                    'planning': '计划',
                    'preparing': '准备',
                    'readying': '准备',
                    'arranging': '安排',
                    'organizing': '组织',
                    'systematizing': '系统化',
                    'methodizing': ' methodize',
                    'structuring': '构建',
                    'ordering': '订购',
                    'regulating': '规范',
                    'adjusting': '调整',
                    'adapting': '适应',
                    'modifying': '修改',
                    'altering': '改变',
                    'changing': '改变',
                    'varying': '变化',
                    'differing': '不同',
                    'diverging': '分歧',
                    'deviating': '偏离',
                    'departing': '离开',
                    'straying': '偏离',
                    'wandering': '游荡',
                    'roaming': '漫游',
                    'rambling': '漫步',
                    'meandering': '蜿蜒',
                    'zigzagging': '之字形',
                    'crisscrossing': '交叉',
                    'intersecting': '相交',
                    'crossing': '穿越',
                    'traversing': '横渡',
                    'spanning': '跨越',
                    'bridging': '架桥',
                    'connecting': '连接',
                    'linking': '链接',
                    'joining': '加入',
                    'uniting': '联合',
                    'allying': '结盟',
                    'associating': '联系',
                    'relating': '关联',
                    'correlating': '相关',
                    'matching': '匹配',
                    'pairing': '配对',
                    'coupling': '耦合',
                    'combining': '结合',
                    'integrating': '整合',
                    'fusing': '融合',
                    'merging': '合并',
                    'blending': '混合',
                    'mixing': '混合',
                    'mingling': ' mingling',
                    'intermingling': ' intermingle',
                    'coalescing': '合并',
                    'amalgamating': '合并',
                    'consolidating': '整合',
                    'synthesizing': '合成',
                    'composing': '组成',
                    'constituting': '构成',
                    'forming': '形成',
                    'making': '制造',
                    'creating': '创造',
                    'producing': '生产',
                    'generating': '生成',
                    'manufacturing': '制造',
                    'fabricating': '制造',
                    'constructing': '建设',
                    'building': '建筑',
                    'erecting': '竖立',
                    'raising': '提高',
                    'lifting': '举起',
                    'hoisting': '吊起',
                    'heaving': ' heave',
                    'hurling': '投掷',
                    'throwing': '投掷',
                    'tossing': '抛',
                    'flinging': ' fling',
                    'casting': '投',
                    'pitching': ' pitch',
                    'slinging': ' sling',
                    'shooting': '射击',
                    'firing': '开火',
                    'launching': '发射',
                    'projecting': ' project',
                    'propelling': '推进',
                    'driving': '驾驶',
                    'pushing': '推',
                    'shoving': '推',
                    'pressing': '压',
                    'compressing': '压缩',
                    'squeezing': '挤压',
                    'crushing': '压碎',
                    'squashing': ' squash',
                    'flattening': ' flatten',
                    'smoothing': '平滑',
                    'leveling': ' leveling',
                    'grading': ' grading',
                    'equalizing': ' equalize',
                    'standardizing': '标准化',
                    'normalizing': '标准化',
                    'regularizing': ' regularize',
                    'stabilizing': '稳定',
                    'steady': '稳定',
                    'stabilizing': ' stabilizing',
                    'balancing': '平衡',
                    'equilibrating': ' equilibrate',
                    'harmonizing': '协调',
                    'synchronizing': '同步',
                    'coordinating': '协调',
                    'aligning': '对齐',
                    'orienting': '定向',
                    'positioning': '定位',
                    'placing': '放置',
                    'putting': '放',
                    'setting': '设置',
                    'laying': '铺设',
                    'installing': '安装',
                    'establishing': '建立',
                    'founding': '创立',
                    'instituting': '建立',
                    'creating': '创造',
                    'originating': '起源',
                    'initiating': '启动',
                    'starting': '开始',
                    'beginning': '开始',
                    'commencing': '开始',
                    'opening': '打开',
                    'launching': '启动',
                    'kicking off': ' kick off',
                    'getting underway': ' get underway',
                    'starting up': '启动',
                    'booting up': ' boot up',
                    'powering up': ' power up',
                    'turning on': '打开',
                    'switching on': ' switch on',
                    'activating': '激活',
                    'enabling': '启用',
                    'empowering': '授权',
                    'authorizing': '授权',
                    'permitting': '允许',
                    'allowing': '允许',
                    'letting': '让',
                    'enabling': ' enabling',
                    'facilitating': '促进',
                    'easing': '缓解',
                    'smoothing': ' smoothing',
                    'simplifying': '简化',
                    'streamlining': '精简',
                    'optimizing': '优化',
                    'perfecting': '完善',
                    'refining': '完善',
                    'polishing': ' polish',
                    'finishing': '完成',
                    'completing': '完成',
                    'finalizing': '定稿',
                    'concluding': '结束',
                    'closing': '关闭',
                    'ending': '结束',
                    'terminating': '终止',
                    'stopping': '停止',
                    'halting': '停止',
                    'ceasing': '停止',
                    'quitting': '退出',
                    'exiting': '退出',
                    'leaving': '离开',
                    'departing': '离开',
                    'going': '去',
                    'coming': '来',
                    'arriving': '到达',
                    'reaching': '到达',
                    'getting': '得到',
                    'obtaining': '获得',
                    'acquiring': '获得',
                    'gaining': '获得',
                    'winning': '赢得',
                    'earning': '赚取',
                    'deserving': '值得',
                    'meriting': ' merit',
                    'warranting': ' warrant',
                    'justifying': ' justify',
                    'validating': ' validate',
                    'verifying': ' verify',
                    'confirming': ' confirm',
                    'proving': ' prove',
                    'demonstrating': ' demonstrate',
                    'showing': ' show',
                    'displaying': ' display',
                    'exhibiting': ' exhibit',
                    'revealing': ' reveal',
                    'disclosing': ' disclose',
                    'uncovering': ' uncover',
                    'unveiling': ' unveil',
                    'exposing': ' expose',
                    'discovering': ' discover',
                    'finding': ' find',
                    'detecting': ' detect',
                    'sensing': ' sense',
                    'feeling': ' feel',
                    'perceiving': ' perceive',
                    'noticing': ' notice',
                    'observing': ' observe',
                    'watching': ' watch',
                    'viewing': ' view',
                    'seeing': ' see',
                    'looking': ' look',
                    'regarding': ' regard',
                    'considering': ' consider',
                    'contemplating': ' contemplate',
                    'pondering': ' ponder',
                    'reflecting': ' reflect',
                    'thinking': ' think',
                    'reasoning': ' reason',
                    'concluding': ' conclude',
                    'inferring': ' infer',
                    'deducing': ' deduce',
                    'deriving': ' derive',
                    'extracting': ' extract',
                    'obtaining': ' obtain',
                    'getting': ' get',
                    'acquiring': ' acquire',
                    'procuring': ' procure',
                    'securing': ' secure',
                    'gaining': ' gain',
                    'winning': ' win',
                    'achieving': ' achieve',
                    'accomplishing': ' accomplish',
                    'attaining': ' attain',
                    'realizing': ' realize',
                    'fulfilling': ' fulfill',
                    'satisfying': ' satisfy',
                    'meeting': ' meet',
                    'suiting': ' suit',
                    'fitting': ' fit',
                    'matching': ' match',
                    'corresponding': ' correspond',
                    'agreeing': ' agree',
                    'consenting': ' consent',
                    'acceding': ' accede',
                    'assenting': ' assent',
                    'accepting': ' accept',
                    'receiving': ' receive',
                    'taking': ' take',
                    'getting': ' get',
                    'obtaining': ' obtain',
                    'acquiring': ' acquire',
                    'procuring': ' procure',
                    'buying': ' buy',
                    'purchasing': ' purchase',
                    'ordering': ' order',
                    'booking': ' book',
                    'reserving': ' reserve',
                    'scheduling': ' schedule',
                    'planning': ' plan',
                    'organizing': ' organize',
                    'arranging': ' arrange',
                    'preparing': ' prepare',
                    'getting ready': ' get ready',
                    'setting up': ' set up',
                    'putting up': ' put up',
                    'building': ' build',
                    'constructing': ' construct',
                    'erecting': ' erect',
                    'raising': ' raise',
                    'elevating': ' elevate',
                    'lifting': ' lift',
                    'hoisting': ' hoist',
                    'heaving': ' heave',
                    'boosting': ' boost',
                    'increasing': ' increase',
                    'raising': ' raise',
                    'heightening': ' heighten',
                    'intensifying': ' intensify',
                    'strengthening': ' strengthen',
                    'reinforcing': ' reinforce',
                    'enhancing': ' enhance',
                    'augmenting': ' augment',
                    'supplementing': ' supplement',
                    'adding': ' add',
                    'appending': ' append',
                    'attaching': ' attach',
                    'affixing': ' affix',
                    'fastening': ' fasten',
                    'fixing': ' fix',
                    'securing': ' secure',
                    'anchoring': ' anchor',
                    'mooring': ' moor',
                    'docking': ' dock',
                    'berthing': ' berth',
                    'parking': ' park',
                    'stationing': ' station',
                    'posting': ' post',
                    'positioning': ' position',
                    'placing': ' place',
                    'putting': ' put',
                    'setting': ' set',
                    'laying': ' lay',
                    'installing': ' install',
                    'establishing': ' establish',
                    'founding': ' found',
                    'creating': ' create',
                    'making': ' make',
                    'building': ' build',
                    'constructing': ' construct',
                    'forming': ' form',
                    'shaping': ' shape',
                    'molding': ' mold',
                    'casting': ' cast',
                    'forging': ' forge',
                    'fabricating': ' fabricate',
                    'manufacturing': ' manufacture',
                    'producing': ' produce',
                    'generating': ' generate',
                    'creating': ' create'
                };
                
                // 翻译函数
                function translateText(text) {
                    let result = text;
                    let hasTranslation = false;
                    
                    Object.keys(dict).forEach(en => {
                        const regex = new RegExp('\\b' + en + '\\b', 'gi');
                        if (regex.test(result)) {
                            result = result.replace(regex, dict[en]);
                            hasTranslation = true;
                        }
                    });
                    
                    return { text: result, translated: hasTranslation };
                }
                
                // 翻译页面内容
                function translatePage() {
                    // 翻译新闻标题
                    const headlines = document.querySelectorAll('h1, h2, h3, h4, .headline, [class*="title"], [class*="headline"]');
                    
                    headlines.forEach(el => {
                        if (el.dataset.translated) return;
                        
                        const original = el.textContent.trim();
                        if (original.length < 5) return;
                        
                        const result = translateText(original);
                        if (result.translated) {
                            el.textContent = result.text + ' [译]';
                            el.style.color = '#0066cc';
                            el.dataset.translated = 'true';
                        }
                    });
                    
                    // 翻译新闻摘要
                    const summaries = document.querySelectorAll('p, .summary, [class*="summary"], [class*="description"]');
                    
                    summaries.forEach(el => {
                        if (el.dataset.translated) return;
                        
                        const original = el.textContent.trim();
                        if (original.length < 20) return;
                        
                        const result = translateText(original);
                        if (result.translated) {
                            el.textContent = result.text;
                            el.style.borderLeft = '3px solid #0066cc';
                            el.style.paddingLeft = '8px';
                            el.dataset.translated = 'true';
                        }
                    });
                    
                    console.log('[WorldMonitor] Translation applied');
                }
                
                // 立即翻译
                setTimeout(translatePage, 2000);
                
                // 监听新内容
                const observer = new MutationObserver(() => {
                    setTimeout(translatePage, 500);
                });
                
                observer.observe(document.body, {
                    childList: true,
                    subtree: true
                });
                
                // 创建翻译按钮
                const btn = document.createElement('div');
                btn.innerHTML = '🌐 翻译';
                btn.style.cssText = `
                    position: fixed;
                    top: 10px;
                    right: 10px;
                    background: rgba(0,123,255,0.9);
                    color: white;
                    padding: 8px 16px;
                    border-radius: 4px;
                    cursor: pointer;
                    z-index: 999999;
                    font-size: 14px;
                    font-family: -apple-system, BlinkMacSystemFont, sans-serif;
                `;
                btn.onclick = translatePage;
                document.body.appendChild(btn);
                
            })();
        """.trimIndent()
        
        webView.evaluateJavascript(script, null)
    }
    
    /**
     * 设置中文语言
     */
    private fun setChineseLanguage() {
        val script = """
            (function() {
                localStorage.setItem('language', 'zh');
                localStorage.setItem('locale', 'zh-CN');
                
                // 触发语言切换
                const selector = document.querySelector('select[name="language"], .language-selector');
                if (selector) {
                    selector.value = 'zh';
                    selector.dispatchEvent(new Event('change'));
                }
            })();
        """.trimIndent()
        
        webView.evaluateJavascript(script, null)
    }
    
    /**
     * 隐藏系统UI
     */
    private fun hideSystemUI() {
        window.decorView.systemUiVisibility = (
            View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY
            or View.SYSTEM_UI_FLAG_FULLSCREEN
            or View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
            or View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
            or View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
        )
    }
    
    override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)
        if (hasFocus) hideSystemUI()
    }
    
    override fun onKeyDown(keyCode: Int, event: KeyEvent?): Boolean {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            if (webView.canGoBack()) {
                webView.goBack()
            }
            return true
        }
        return super.onKeyDown(keyCode, event)
    }
    
    override fun onResume() {
        super.onResume()
        hideSystemUI()
        webView.onResume()
    }
    
    override fun onPause() {
        super.onPause()
        webView.onPause()
    }
    
    override fun onDestroy() {
        webView.destroy()
        super.onDestroy()
    }
}
